---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Análise de Crédito

<!-- badges: start -->
<!-- badges: end -->



##### Pacotes utilizados na análise
```{r message=FALSE}
library(odbc)
library(tidyverse)
library(questionr)
library(knitr)


```



```{r include=FALSE}
con <- dbConnect(odbc(),
                 Driver = "ODBC Driver 17 for SQL Server",
                 Server = "VINIPC",
                 Database = "projetobank",
                 UID = "sa",
                 PWD = '2510@vini',
                 Port = 8070)

```


##### Estabelece a conexão com o banco de dados SQL Server 2017, para extração dos dados. 

```{r eval = FALSE}
con <- dbConnect(odbc(),
                 Driver = "ODBC Driver 17 for SQL Server",
                 Server = "##",
                 Database = "projetobank",
                 UID = "##",
                 PWD = '##',
                 Port ='##')
```


##### Carregando os dados do banco pro R. 

```{r}

df_bank_train <- dbGetQuery(con, 'SELECT * FROM bank_test')

```

##### Ajustando os nomes das variáveis
```{r}

df_bank_train <-  janitor::clean_names(df_bank_train)

```

##### Info dos dados
```{r}

glimpse(df_bank_train)
```

##### Existem dados faltantes no conjunto de dados? 
```{r}
nas <- freq.na(df_bank_train)
kable(nas)
```




